### ISSUE TITLE
When will the weight and inference code be open sourced?

### ISSUE THREAD

**Issue by plastic0313** [TencentQQGYLab/ELLA#16]
Your work is very meaningful and can bring more playability to the existing ecosystem based on sd1.5 and sd xl. When will it be open sourced? and hopefully SD XL will be open sourced too

**Comment by foureyednymph** [comment]
still waiting..

**Comment by kelisiya** [comment]
+1

**Comment by melohux** [comment]
Thank you for your patience and here comes our voice! ELLA-SD1.5 is now released. Welcome to try! 🥰

**Comment by Subarasheese** [comment]
Yeah; please let us know if the SDXL version will ever be released. I know you guys mentioned it requires "extensive review", but a definitive answer would be good

**Comment by TencentQQGY** [comment]
SDXL version will not be released, thanks.

**Comment by Cleroth** [comment]
So, useless. Back to waiting for SD3 I guess.

**Comment by scarbain** [comment]
> SDXL version will not be released, thanks.

Thank you for clarifying it :) 

Could you at least provide the training code you used ? That would be absolutely amazing!

**Comment by scarbain** [comment]
> SDXL version will not be released, thanks.

Thank you for clarifying it @TencentQQGY @melohux :)

Could you at least provide the training code you used ? That would be absolutely amazing!

**Comment by Charuru** [comment]
> SDXL version will not be released, thanks.

Guys if you don't release it this will make very little to almost no impact. The community will move to alternate solutions soon with SD3 or RPG Master. This is your chance to make Tencent a leader in image generation, preempt SD3 before it comes out.

**Comment by kubernetes-bad** [comment]
Leader in image creation?! Tencent is *known* for releasing half-working or straight up broken things.
I was very hyped for ELLA's release, but after about a month of waiting they release... this. And there's no training data, no finetuning scripts, paper skips over the most important implementation details etc. - all too typical of Tencent project qualities.
And now this "announcement" that SD XL adapter will not be released - this is Tencent's spit into community's face. Abhorrent.

As it stands right now, ELLA has serious quality problem. See https://github.com/kijai/ComfyUI-ELLA-wrapper/issues/3

![ELLA](https://private-user-images.githubusercontent.com/153952949/320989254-9b8a2359-e16a-4357-a442-52eb018a358a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzQwNzMsIm5iZiI6MTcxMjc3Mzc3MywicGF0aCI6Ii8xNTM5NTI5NDkvMzIwOTg5MjU0LTliOGEyMzU5LWUxNmEtNDM1Ny1hNDQyLTUyZWIwMThhMzU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxODI5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTE5OTc0ODNhMTk5M2Q2M2U1YzIxNmJmZDZmMTJjZDA3NzUxNWVmNWZkMmE0NjFmMjM0ZDYwZmRlNjljNmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vcdHun_i19xU_UvqpPIqe0LgR0JpE5zlow2Qm-VWVCo)
*M A S T E R P I E C E* 👌 

And to be frank with you - I do not care if they ever fix this: I'm moving on.

There are two alternative projects that achieve more or less same thing:
- https://github.com/ShihaoZhaoZSH/LaVi-Bridge - currently has just SD1.4 adapter, but they're working on SD XL one.
- https://github.com/litwellchi/M2Chat - impressive paper, but code and checkpoints are yet to be released.

Next time, when Tencent folks put out a paper promising SOTA in next 2 weeks - be wary, maybe.

**Comment by chrish-slingshot** [comment]
> Leader in image creation?! Tencent is _known_ for releasing half-working or straight up broken things. I was very hyped for ELLA's release, but after about a month of waiting they release... this. And there's no training data, no finetuning scripts, paper skips over the most important implementation details etc. - all too typical of Tencent project qualities. And now this "announcement" that SD XL adapter will not be released - this is Tencent's spit into community's face. Abhorrent.
> 
> As it stands right now, ELLA has serious quality problem. See [kijai/ComfyUI-ELLA-wrapper#3](https://github.com/kijai/ComfyUI-ELLA-wrapper/issues/3)
> 
> ![ELLA](https://private-user-images.githubusercontent.com/153952949/321366657-b81ef462-2753-4ba2-8afe-794783a91ea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Nzc3NjIsIm5iZiI6MTcxMjc3NzQ2MiwicGF0aCI6Ii8xNTM5NTI5NDkvMzIxMzY2NjU3LWI4MWVmNDYyLTI3NTMtNGJhMi04YWZlLTc5NDc4M2E5MWVhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxOTMxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzQzNGJkOWJkZDMxNWRjYThhZTFiMzFhM2ZmY2ZkMmRlNGNlNWE2OTdhZTkyODg0OGRjNzYwZWFkNmUxY2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5otklVL7OzrCYz_G-cNag45fmuq50RcGW19efHmqHCg)
> 
> _M A S T E R P I E C E_ 👌
> 
> And to be frank with you - I do not care if they ever fix this: I'm moving on.
> 
> There are two alternative projects that achieve more or less same thing:
> 
> * https://github.com/ShihaoZhaoZSH/LaVi-Bridge - currently has just SD1.4 adapter, but they're working on SD XL one.
> * https://github.com/litwellchi/M2Chat - impressive paper, but code and checkpoints are yet to be released.
> 
> Next time, when Tencent folks put out a paper promising SOTA in next 2 weeks - be wary, maybe.

I think this is being unnecessarily unfair. The weights literally only just released, and there is a separate implementation to the one in that repository you linked which is making progress with improving quality. Furthermore the prompt adherence in ELLA for 1.5 is astounding, and can be used to create an initial image to then process through img2img to improve quality.

For a model that's only been out for 2 days I think it needs more time for the community to see what they can do with it.

**Comment by Nebuluss** [comment]
So disappointed. I had high hopes for SDXL since SD3 might never be released

**Comment by JelloWizard** [comment]
> > SDXL version will not be released, thanks.
> 
> Guys if you don't release it this will make very little to almost no impact. The community will move to alternate solutions soon with SD3 or RPG Master. This is your chance to make Tencent a leader in image generation, preempt SD3 before it comes out.

RPG Master???

**Comment by camoody1** [comment]
> > > SDXL version will not be released, thanks.
> > 
> > 
> > Guys if you don't release it this will make very little to almost no impact. The community will move to alternate solutions soon with SD3 or RPG Master. This is your chance to make Tencent a leader in image generation, preempt SD3 before it comes out.
> 
> RPG Master???

@JelloWizard https://github.com/YangLing0818/RPG-DiffusionMaster

**Comment by aimerib** [comment]
I'd like to echo the sentiment that the readme needs updating. I wasted a few days looking into ELLA only to find out it is a dead research with no impact to the community whatsoever. I'd go as far as archive the repo.

**Comment by kjerk** [comment]
> SDXL version will not be released, thanks.

It's been ~14 months now and SDXL is (mostly) outmoded by Flux or HiDream, or Video gen, GPT-4o, etc. Could you consider releasing the weights for ELLA-SDXL now as it's likely no longer a commercially competitive issue? SDXL is still widely used and could still benefit from the preexisting research, and it would be nice to see the fruit of the research hit wider use if people find such a use for it.
