### ISSUE TITLE
How to use it in WEBUI or COMFYUI?

### ISSUE THREAD

**Issue by aimarxjg** [TencentQQGYLab/ELLA#18]
I used it as a normal 1.5LORA with SD1.5 to generate pictures, in COMFYUI，but it didn't have the advertised effect

**Comment by bakkot** [comment]
It's not a LoRa; it requires custom nodes. Try [this plugin](https://github.com/kijai/ComfyUI-ELLA-wrapper).

**Comment by ExponentialML** [comment]
https://github.com/ExponentialML/ComfyUI_ELLA/

**Comment by aimarxjg** [comment]
> It's not a LoRA; it requires custom nodes. Try [this plugin](https://github.com/kijai/ComfyUI-ELLA-wrapper).

THX~

**Comment by aimarxjg** [comment]
> https://github.com/ExponentialML/ComfyUI_ELLA/

THx~
