### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by scarbain** [TencentQQGYLab/ELLA#19]
Hello,

Thank you for this release, the capabilities of SD1.5 are infinitely better with ELLA !

Are you planning on releasing the training code? If yes, any idea when ?

Thanks

**Comment by Metal079** [comment]
That would be amazing, unfortunetly the model as is doesnt really work for my model so being able to finetune would be amazing.
![racoon_apple_Qwen-72B-Chat-refined](https://github.com/TencentQQGYLab/ELLA/assets/7731400/ded0f141-f277-4ea0-85f4-187869a3da72)
![red_book-yellow_vase](https://github.com/TencentQQGYLab/ELLA/assets/7731400/7474c8f8-f697-4f65-a10b-74c00334d330)
![red_book-yellow_vase-gpt4_refined_caption](https://github.com/TencentQQGYLab/ELLA/assets/7731400/a713f26d-9c84-46a9-9ce6-deae0ad008d9)
![wombat](https://github.com/TencentQQGYLab/ELLA/assets/7731400/283b5808-8940-42a3-9e52-b5155e383ec7)

**Comment by budui** [comment]
Hi, Our training code is based on IP-Adapter's training code: https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train.py. The changes mainly focus on letting the optimizer optimize ELLA instead of IP-Adapter, and the data loading part.
