### ISSUE TITLE
ELLA generate img quality is worse than origin model

### ISSUE THREAD

**Issue by akk-123** [TencentQQGYLab/ELLA#20]
ELLA has stronger text understanding capabilities, but the image quality is worse

![image](https://github.com/TencentQQGYLab/ELLA/assets/98469560/da9aecd7-0616-4745-aab7-31321edb148c)
![image](https://github.com/TencentQQGYLab/ELLA/assets/98469560/d324294c-d9ef-4837-85b2-e5e5ac190caf)

**Comment by budui** [comment]
Hi, can you share the base Model and prompt you use?  We need to debug ella with them. Additionally, we have updated our README with some tips on how to better utilize ELLA, which you may find helpful.

**Comment by akk-123** [comment]
base model: https://civitai.com/models/15003/cyberrealistic
prompt: a woman, pink hair, wearing blue baseball cap, wearning sunglasses,  green scarf, yellow sweater
I found that high cfg scale will cause img blur and noise, decrease cfg(for example cfg=3) will get better quality img

what' more, ELLA's text understanding ability does not perform so well in multi-person situations
promt: a man and and a woman, woman standing left,  pink hair, wearing blue baseball cap, wearing earrings and necklace,  green scarf, yellow sweater; man standing right, wearing sunglasses and blue t-shirt
![image](https://github.com/TencentQQGYLab/ELLA/assets/98469560/cfeeeafa-a46f-4991-ba47-7796601919aa)
![image](https://github.com/TencentQQGYLab/ELLA/assets/98469560/fcc86425-ccf0-4c1b-98d3-d04bb213d0ac)

**Comment by scarbain** [comment]
From my testings, using plain English prompts helps a lot compared to using keywords. Also, be careful of the negative prompt you're using and the size of generation, a different size than 512x512 is not resulting in good generations for me

**Comment by budui** [comment]
> using plain English prompts helps a lot compared to using keywords.

Indeed, because we mainly use synthetic captions similar to pure English to train ella

You can refer to test examples from the community: https://imgur.com/a/FhWpSSb

![image](https://github.com/TencentQQGYLab/ELLA/assets/16448529/8b220fc5-c030-4e1c-a96f-d1f7883beeda)

**Comment by budui** [comment]
This caption may still be too difficult for ella-sd1.5. 😥

Refined caption by me:

> A man and a woman are standing together, the woman on the left and the man on the right. The woman has pink hair, a blue basketball cap, earrings and a necklace, and a green scarf and yellow sweater. Man wearing sunglasses and blue shirt.

<img width="1129" alt="企业微信截图_17127426516883" src="https://github.com/TencentQQGYLab/ELLA/assets/16448529/b5f328da-6bff-4a6d-a048-eb451f6db98e">

Refined caption by Qwen:

> A couple stands side by side, creating an eye-catching visual display of contrasting styles. The woman, positioned to the left, sports vibrant pink hair that falls just past her shoulders, complemented by a blue baseball cap adorned with intricate earrings and a necklace. She wraps herself in a green scarf for warmth and wears a sunny yellow sweater, adding pops of color to the scene. On the other hand, the man, standing to the right, exudes coolness with his sunglasses, donning a casual blue t-shirt. Both individuals seem to be enjoying each other's company amidst their unique fashion choices.

![image](https://github.com/TencentQQGYLab/ELLA/assets/16448529/c38126d4-1a6c-46f7-a36f-606c3b294d29)

Refined caption by GPT4:

> A woman with vibrant pink hair stands to the left, her head adorned with a blue baseball cap. She's wearing a pair of shiny earrings and a necklace that glimmers under the light. Wrapped around her neck is a green scarf, contrasting with her bright yellow sweater. To her right stands a man, his eyes hidden behind a pair of dark sunglasses. He's casually dressed in a blue t-shirt, his hands tucked into his pockets.

![image](https://github.com/TencentQQGYLab/ELLA/assets/16448529/f013ea12-8d31-4acc-b4c1-93057bda4430)

**Comment by akk-123** [comment]
so, Looking forward to sdxl !!

**Comment by scarbain** [comment]
> This caption may still be too difficult for ella-sd1.5. 😥
> 
> 
> 
> Refined caption by me:
> 
> 
> 
> > A man and a woman are standing together, the woman on the left and the man on the right. The woman has pink hair, a blue basketball cap, earrings and a necklace, and a green scarf and yellow sweater. Man wearing sunglasses and blue shirt.
> 
> 
> 
> <img width="1129" alt="企业微信截图_17127426516883" src="https://github.com/TencentQQGYLab/ELLA/assets/16448529/b5f328da-6bff-4a6d-a048-eb451f6db98e">
> 
> 
> 
> Refined caption by Qwen:
> 
> 
> 
> > A couple stands side by side, creating an eye-catching visual display of contrasting styles. The woman, positioned to the left, sports vibrant pink hair that falls just past her shoulders, complemented by a blue baseball cap adorned with intricate earrings and a necklace. She wraps herself in a green scarf for warmth and wears a sunny yellow sweater, adding pops of color to the scene. On the other hand, the man, standing to the right, exudes coolness with his sunglasses, donning a casual blue t-shirt. Both individuals seem to be enjoying each other's company amidst their unique fashion choices.
> 
> 
> 
> ![image](https://github.com/TencentQQGYLab/ELLA/assets/16448529/c38126d4-1a6c-46f7-a36f-606c3b294d29)
> 
> 
> 
> Refined caption by GPT4:
> 
> 
> 
> > A woman with vibrant pink hair stands to the left, her head adorned with a blue baseball cap. She's wearing a pair of shiny earrings and a necklace that glimmers under the light. Wrapped around her neck is a green scarf, contrasting with her bright yellow sweater. To her right stands a man, his eyes hidden behind a pair of dark sunglasses. He's casually dressed in a blue t-shirt, his hands tucked into his pockets.
> 
> 
> 
> ![image](https://github.com/TencentQQGYLab/ELLA/assets/16448529/f013ea12-8d31-4acc-b4c1-93057bda4430)
> 
> 
> 
> 

Have you tried finetuning SD1.5 with randomly using T5 with your adapter or clip ? 
Since your adapter only acts on the caption side, maybe having a full Unet finetuned with proper captions (using CogVLM for example) + randomly selecting a different text encoder at each step, could help it even more ?

**Comment by scarbain** [comment]
Of course we would freeze clip and your adapter and only finetune unet

**Comment by budui** [comment]
@scarbain I think randomly selecting text encoder during training is a very interesting idea, which can make UNet adapt to both CLIP and ELLA.  However, due to resource constraints and limited usage scenarios, we prefer to train some Adapters instead of fine-tuning UNet. We will try to train ELLA as a branch of IP-Adapter later. Maybe IP-Adapter+ELLA will be more practical?

**Comment by scarbain** [comment]
It could be interesting to train a LoRA only instead of full FT of unet. And using this LoRA when using ELLA. Kind of like a LCM LoRA in usage.
I'll try that and report back if it provides good results.

**Comment by andupotorac** [comment]
> It could be interesting to train a LoRA only instead of full FT of unet. And using this LoRA when using ELLA. Kind of like a LCM LoRA in usage. I'll try that and report back if it provides good results.

How did it go?

**Comment by andupotorac** [comment]
> This caption may still be too difficult for ella-sd1.5. 😥
> 
> Refined caption by me:
> 
> > A man and a woman are standing together, the woman on the left and the man on the right. The woman has pink hair, a blue basketball cap, earrings and a necklace, and a green scarf and yellow sweater. Man wearing sunglasses and blue shirt.
> 
> <img alt="企业微信截图_17127426516883" width="1129" src="https://private-user-images.githubusercontent.com/16448529/321187428-b5f328da-6bff-4a6d-a048-eb451f6db98e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzIyNTEsIm5iZiI6MTcyMTczMTk1MSwicGF0aCI6Ii8xNjQ0ODUyOS8zMjExODc0MjgtYjVmMzI4ZGEtNmJmZi00YTZkLWEwNDgtZWI0NTFmNmRiOThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEwNTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNzYxYTFlMzI1YjBjMTY5YjdlMGQ2M2JjMzkzZjEzNjgzMDE4OGRlY2NmMTExNTk2NTRmYmE0ZGNlNGZmOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6SV_J-VUCFx4yrIreSz5b79J6DpemxKQRLcuMTQHpI">
> Refined caption by Qwen:
> 
> > A couple stands side by side, creating an eye-catching visual display of contrasting styles. The woman, positioned to the left, sports vibrant pink hair that falls just past her shoulders, complemented by a blue baseball cap adorned with intricate earrings and a necklace. She wraps herself in a green scarf for warmth and wears a sunny yellow sweater, adding pops of color to the scene. On the other hand, the man, standing to the right, exudes coolness with his sunglasses, donning a casual blue t-shirt. Both individuals seem to be enjoying each other's company amidst their unique fashion choices.
> 
> ![image](https://private-user-images.githubusercontent.com/16448529/321189219-c38126d4-1a6c-46f7-a36f-606c3b294d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzIyNTEsIm5iZiI6MTcyMTczMTk1MSwicGF0aCI6Ii8xNjQ0ODUyOS8zMjExODkyMTktYzM4MTI2ZDQtMWE2Yy00NmY3LWEzNmYtNjA2YzNiMjk0ZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEwNTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDIwNmY0MmQ5YzI4YTQyNzZlODgxZDIyOWMwZGIyNjc2YjFmNWMyOGYxOTg5ZGQ4ZGIyN2NlOGZhM2YxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cvnu60mn7qm7wlO8_3bbEfHr_4z-LibLYPjOV9nQiQQ)
> 
> Refined caption by GPT4:
> 
> > A woman with vibrant pink hair stands to the left, her head adorned with a blue baseball cap. She's wearing a pair of shiny earrings and a necklace that glimmers under the light. Wrapped around her neck is a green scarf, contrasting with her bright yellow sweater. To her right stands a man, his eyes hidden behind a pair of dark sunglasses. He's casually dressed in a blue t-shirt, his hands tucked into his pockets.
> 
> ![image](https://private-user-images.githubusercontent.com/16448529/321189976-f013ea12-8d31-4acc-b4c1-93057bda4430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzIyNTEsIm5iZiI6MTcyMTczMTk1MSwicGF0aCI6Ii8xNjQ0ODUyOS8zMjExODk5NzYtZjAxM2VhMTItOGQzMS00YWNjLWI0YzEtOTMwNTdiZGE0NDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEwNTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjhmNjUzZmJjNzQ4MjhiZTNlN2M2YWNhNGUxOGZjYTRjMjNjMDI5MDY2ODQyZmVlOTEwZDc3NmE2MjJkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TLQFTDJB9LxNuX5I0i3eM12r5DlqYMiDNcvFpnKrYIs)

Where are you demo-ing these? Is there a HuggingFace demo we can use?
