### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge error when i use ella in kaggle 

### ISSUE THREAD

**Issue by SanicsP** [TencentQQGYLab/ELLA#28]
my code : 
!git clone https://github.com/TencentQQGYLab/ELLA
!wget --compression=none https://huggingface.co/QQGYLab/ELLA/blob/main/ella-sd1.5-tsc-t5xl.safetensors
!pip install -U gradio fire diffusers

!GRADIO_SERVER_NAME=0.0.0.0 GRADIO_SERVER_PORT=8082 python3 ELLA/inference.py demo /kaggle/working/ella-sd1.5-tsc-t5xl.safetensors

**Comment by budui** [comment]
You should use `git lfs ...` instead of `wget` to download https://huggingface.co/QQGYLab/ELLA/blob/main/ella-sd1.5-tsc-t5xl.safetensors
