### ISSUE TITLE
is there an expected timeline for release of ELLA model?

### ISSUE THREAD

**Issue by TruthSearcher** [TencentQQGYLab/ELLA#3]

**Comment by fangyixiao18** [comment]
We will release our models in 1 week. Thanks for your issue, please stay tuned.

**Comment by ninjasaid2k** [comment]
>We will release our models in 1 week. Thanks for your issue, please stay tuned.

is there an update on the models?

**Comment by Cleroth** [comment]
> > We will release our models in 1 week. Thanks for your issue, please stay tuned.
> 
> is there an update on the models?

https://github.com/TencentQQGYLab/ELLA/commit/b0df94b13559f4af2c68c3c8e0516f113b18b8a6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R61

**Comment by fangyixiao18** [comment]
Thank you for your patience! ELLA-SD1.5 is now released. Welcome to try!

**Comment by Jonseed** [comment]
The checkpoint is 134 MB? How do you use it?
