### ISSUE TITLE
About ELLA models

### ISSUE THREAD

**Issue by Sickatt** [TencentQQGYLab/ELLA#31]
Hello, sorry for the silly question but i dont see the info anywhere.
I download all the models:
flax_model-00001-of-00002
flax_model-00002-of-00002
model-00001-of-00002
model-00002-of-00002
pytorch_model-00001-of-00002
pytorch_model-00002-of-00002
tf_model-00001-of-00002
tf_model-00002-of-00002

I need all of them?
Or i need one of each (1flax, 1model, 1pytorch, 1tf_model) ?
And what is the difference of using the 1-2 Gb files vs the almost 10Gb ones?
Thanks!!

**Comment by budui** [comment]
The repo `google/flan-t5-xl` contains the weights of PyTorch and TF for T5Encoder, T5Decoder, etc. In fact, ELLA only needs the weights of the fp16 version of T5EncoderModel. 

refer to https://github.com/ExponentialML/ComfyUI_ELLA/issues/4 for more information

**Comment by Sickatt** [comment]
Oh, i never said im using ComfyUI, when looking for the models i added to flan-t5-xl i found a new folder ... the one you said, "fp16" one ... only needed delete the one i created ... you save me more than 40Gb of disk space, thanks budui
