### ISSUE TITLE
Question about AdaLN implementation.

### ISSUE THREAD

**Issue by liming-ai** [TencentQQGYLab/ELLA#51]
Thanks for your amazing work, I notice that in the paper you mention ELLA utilizes AdaLN instead of AdaLN-Zero. However, in the [released code](https://github.com/TencentQQGYLab/ELLA/blob/3c228f1dc6c4d3cad0a47493816151a419f14db3/model.py#L29), it seems to be AdaLN-Zero. Could you please check it? If you use AdaLN during training, could you please share the initialization algorithms?

**Comment by budui** [comment]
AdaLN-zero use more params in Residual Path. 

 initialization algorithms:

``` python
nn.init.zeros_(self.linear.weight)
nn.init.zeros_(self.linear.bias)
```

**Comment by liming-ai** [comment]
> AdaLN-zero use more params in Residual Path.
> 
> initialization algorithms:
> 
> ```python
> nn.init.zeros_(self.linear.weight)
> nn.init.zeros_(self.linear.bias)
> ```

Thank a lot for your reply. I don't quite understand what you mean `AdaLN-zero use more params in Residual Path`. My question is that according to the published code, ELLA seems to use AdaLN-Zero instead of AdaLN during training since you use `nn.init_zeros` to initialize the scale and shift:
```Python
class AdaLayerNorm(nn.Module):
    def __init__(self, embedding_dim: int, time_embedding_dim: Optional[int] = None):
        super().__init__()

        if time_embedding_dim is None:
            time_embedding_dim = embedding_dim

        self.silu = nn.SiLU()
        self.linear = nn.Linear(time_embedding_dim, 2 * embedding_dim, bias=True)
        nn.init.zeros_(self.linear.weight)
        nn.init.zeros_(self.linear.bias)

        self.norm = nn.LayerNorm(embedding_dim, elementwise_affine=False, eps=1e-6)

    def forward(
        self, x: torch.Tensor, timestep_embedding: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        emb = self.linear(self.silu(timestep_embedding))
        shift, scale = emb.view(len(x), 1, -1).chunk(2, dim=-1)
        x = self.norm(x) * (1 + scale) + shift
        return x
```

As shown in your code, `x = self.norm(x) * (1 + scale) + shift` should be equal to `x` if the `scale` and `shift` is initialized to zero with `nn.init.zeros_(self.linear.weight); nn.init.zeros_(self.linear.bias)`, which means it actually is AdaLN-Zero.

As an opposite, PixArt-α also uses AdaLN rather than AdaLN-Zero, while [their implementation](https://github.com/PixArt-alpha/PixArt-alpha/blob/3e9d36f2f6ba18bb0b122667e1b1c2031a8e06fb/diffusion/model/nets/PixArt_blocks.py#L200) does not contain zero-initialization.

I'm not sure if my understanding here is correct. If not, could you please provide some guidance and explanation?

**Comment by budui** [comment]
You can refer to the description of AdaLN-zero in the paper available at https://arxiv.org/pdf/2212.09748: 

> 'In addition to regressing γ and β, we also regress dimension-wise scaling parameters α that are applied immediately prior to any **residual connections** within the DiT block.'

> 'We initialize the MLP to output the zero-vector for all α; this initializes the full DiT block as the identity function.'

The "zero" in AdaLN-zero refers to initializing the role of the residual path to 0, rather than anything related to weight initialization. Here, I initialize the linear parameters of AdaLN to 0 to ensure that the initial AdaLN is not influenced by the modulation features, but rather gradually increases its influence.

code example: 

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention.py#L442

``` python
norm_hidden_states, gate_msa, shift_mlp, scale_mlp, gate_mlp = self.norm1(
                hidden_states, timestep, class_labels, hidden_dtype=hidden_states.dtype
            )
```

"more params" means `gate_msa` and `gate_mlp`.

**Comment by liming-ai** [comment]
> You can refer to the description of AdaLN-zero in the paper available at https://arxiv.org/pdf/2212.09748:
> 
> > 'In addition to regressing γ and β, we also regress dimension-wise scaling parameters α that are applied immediately prior to any **residual connections** within the DiT block.'
> 
> > 'We initialize the MLP to output the zero-vector for all α; this initializes the full DiT block as the identity function.'
> 
> The "zero" in AdaLN-zero refers to initializing the role of the residual path to 0, rather than anything related to weight initialization. Here, I initialize the linear parameters of AdaLN to 0 to ensure that the initial AdaLN is not influenced by the modulation features, but rather gradually increases its influence.
> 
> code example:
> 
> https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention.py#L442
> 
> ```python
> norm_hidden_states, gate_msa, shift_mlp, scale_mlp, gate_mlp = self.norm1(
>                 hidden_states, timestep, class_labels, hidden_dtype=hidden_states.dtype
>             )
> ```
> 
> "more params" means `gate_msa` and `gate_mlp`.

I got it! Thanks a lot for your explanation! Really appreciate it!
